linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosimple
    - gocritic
    - misspell

linters-settings:
  misspell:
    locale: US

issues:
  exclude-use-default: true
